apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: cloudtalk-backend-config
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 1800
  securityPolicy:
    name: "cloudtalk-security-policy" # 如果您有 Cloud Armor 安全策略
