apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: cloudtalk-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  rateLimit:
    enabled: true
    requestsPerMinute: 1000
    burstSize: 200
  sslPolicy: "GKE_TLS_12"
